module GitHub
  class User < Base

    set_resource 'http://github.com/api/v2/yaml/users', 'user', 'users'

    attr_accessor :name, :company, :location, :created, :repos, :gists,
                  :id, :homepage, :followers, :following, :login, :email,
                  # additional attributes from search:
                  :language, :fullname, :type, :pushed, :score,
                  # generated attributes:
                  :url

    aliases_for :homepage => :blog, :name => :username, :created=> :created_at, :repos => :public_repo_count,
                :gists => :public_gist_count, :followers=> :followers_count, :following=> :following_count

    #TODO: problem with repos - should be collection of repos, NOT just a counter - but it's set by /search
    # isn't it the same for gists, followers, following?

    def initialize options
      super
      raise "Unable to initialize #{self.class} without name" unless @name
      if @login #need to correct attributes generated by /show/:user
        @name, @fullname = @login, @name
        @id = 'user-' + @id
      end
      @url ||= "http://github.com/#{@name}"
      @type ||= "user"
    end

  end
end